/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public class AltaF extends CamGen2Base {
  private long swigCPtr;

  protected AltaF(long cPtr, boolean cMemoryOwn) {
    super(jlibapogeeJNI.AltaF_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AltaF obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jlibapogeeJNI.delete_AltaF(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AltaF() {
    this(jlibapogeeJNI.new_AltaF(), true);
  }

  public void OpenConnection(String ioType, String DeviceAddr, int FirmwareRev, int Id) {
    jlibapogeeJNI.AltaF_OpenConnection(swigCPtr, this, ioType, DeviceAddr, FirmwareRev, Id);
  }

  public void CloseConnection() {
    jlibapogeeJNI.AltaF_CloseConnection(swigCPtr, this);
  }

  public void StartExposure(double Duration, boolean IsLight) {
    jlibapogeeJNI.AltaF_StartExposure(swigCPtr, this, Duration, IsLight);
  }

  public int GetNumAdChannels() {
    return jlibapogeeJNI.AltaF_GetNumAdChannels(swigCPtr, this);
  }

  public void Init() {
    jlibapogeeJNI.AltaF_Init(swigCPtr, this);
  }

  public FanMode GetFanMode() {
    return FanMode.swigToEnum(jlibapogeeJNI.AltaF_GetFanMode(swigCPtr, this));
  }

  public void SetFanMode(FanMode mode, boolean PreCondCheck) {
    jlibapogeeJNI.AltaF_SetFanMode__SWIG_0(swigCPtr, this, mode.swigValue(), PreCondCheck);
  }

  public void SetFanMode(FanMode mode) {
    jlibapogeeJNI.AltaF_SetFanMode__SWIG_1(swigCPtr, this, mode.swigValue());
  }

}
