/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public final class CameraMode {
  public final static CameraMode CameraMode_Normal = new CameraMode("CameraMode_Normal", jlibapogeeJNI.CameraMode_Normal_get());
  public final static CameraMode CameraMode_TDI = new CameraMode("CameraMode_TDI", jlibapogeeJNI.CameraMode_TDI_get());
  public final static CameraMode CameraMode_Test = new CameraMode("CameraMode_Test", jlibapogeeJNI.CameraMode_Test_get());
  public final static CameraMode CameraMode_ExternalTrigger = new CameraMode("CameraMode_ExternalTrigger", jlibapogeeJNI.CameraMode_ExternalTrigger_get());
  public final static CameraMode CameraMode_ExternalShutter = new CameraMode("CameraMode_ExternalShutter", jlibapogeeJNI.CameraMode_ExternalShutter_get());
  public final static CameraMode CameraMode_Kinetics = new CameraMode("CameraMode_Kinetics", jlibapogeeJNI.CameraMode_Kinetics_get());
  public final static CameraMode CameraMode_Unknown = new CameraMode("CameraMode_Unknown", jlibapogeeJNI.CameraMode_Unknown_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CameraMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CameraMode.class + " with value " + swigValue);
  }

  private CameraMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CameraMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CameraMode(String swigName, CameraMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CameraMode[] swigValues = { CameraMode_Normal, CameraMode_TDI, CameraMode_Test, CameraMode_ExternalTrigger, CameraMode_ExternalShutter, CameraMode_Kinetics, CameraMode_Unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

