/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public class Quad extends CamGen2Base {
  private long swigCPtr;

  protected Quad(long cPtr, boolean cMemoryOwn) {
    super(jlibapogeeJNI.Quad_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Quad obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jlibapogeeJNI.delete_Quad(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Quad() {
    this(jlibapogeeJNI.new_Quad(), true);
  }

  public void OpenConnection(String ioType, String DeviceAddr, int FirmwareRev, int Id) {
    jlibapogeeJNI.Quad_OpenConnection(swigCPtr, this, ioType, DeviceAddr, FirmwareRev, Id);
  }

  public void CloseConnection() {
    jlibapogeeJNI.Quad_CloseConnection(swigCPtr, this);
  }

  public void StartExposure(double Duration, boolean IsLight) {
    jlibapogeeJNI.Quad_StartExposure(swigCPtr, this, Duration, IsLight);
  }

  public boolean IsPixelReorderOn() {
    return jlibapogeeJNI.Quad_IsPixelReorderOn(swigCPtr, this);
  }

  public void SetPixelReorder(boolean TurnOn) {
    jlibapogeeJNI.Quad_SetPixelReorder(swigCPtr, this, TurnOn);
  }

  public int GetNumAdChannels() {
    return jlibapogeeJNI.Quad_GetNumAdChannels(swigCPtr, this);
  }

  public void SetIsQuadBit() {
    jlibapogeeJNI.Quad_SetIsQuadBit(swigCPtr, this);
  }

  public void Init() {
    jlibapogeeJNI.Quad_Init(swigCPtr, this);
  }

  public FanMode GetFanMode() {
    return FanMode.swigToEnum(jlibapogeeJNI.Quad_GetFanMode(swigCPtr, this));
  }

  public void SetFanMode(FanMode mode, boolean PreCondCheck) {
    jlibapogeeJNI.Quad_SetFanMode__SWIG_0(swigCPtr, this, mode.swigValue(), PreCondCheck);
  }

  public void SetFanMode(FanMode mode) {
    jlibapogeeJNI.Quad_SetFanMode__SWIG_1(swigCPtr, this, mode.swigValue());
  }

}
