/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public final class Status {
  public final static Status Status_ConnectionError = new Status("Status_ConnectionError", jlibapogeeJNI.Status_ConnectionError_get());
  public final static Status Status_DataError = new Status("Status_DataError", jlibapogeeJNI.Status_DataError_get());
  public final static Status Status_PatternError = new Status("Status_PatternError", jlibapogeeJNI.Status_PatternError_get());
  public final static Status Status_Idle = new Status("Status_Idle", jlibapogeeJNI.Status_Idle_get());
  public final static Status Status_Exposing = new Status("Status_Exposing", jlibapogeeJNI.Status_Exposing_get());
  public final static Status Status_ImagingActive = new Status("Status_ImagingActive", jlibapogeeJNI.Status_ImagingActive_get());
  public final static Status Status_ImageReady = new Status("Status_ImageReady", jlibapogeeJNI.Status_ImageReady_get());
  public final static Status Status_Flushing = new Status("Status_Flushing", jlibapogeeJNI.Status_Flushing_get());
  public final static Status Status_WaitingOnTrigger = new Status("Status_WaitingOnTrigger", jlibapogeeJNI.Status_WaitingOnTrigger_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Status swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Status.class + " with value " + swigValue);
  }

  private Status(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Status(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Status(String swigName, Status swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Status[] swigValues = { Status_ConnectionError, Status_DataError, Status_PatternError, Status_Idle, Status_Exposing, Status_ImagingActive, Status_ImageReady, Status_Flushing, Status_WaitingOnTrigger };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

