/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public class Uint16Vector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Uint16Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Uint16Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jlibapogeeJNI.delete_Uint16Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Uint16Vector() {
    this(jlibapogeeJNI.new_Uint16Vector__SWIG_0(), true);
  }

  public Uint16Vector(long n) {
    this(jlibapogeeJNI.new_Uint16Vector__SWIG_1(n), true);
  }

  public long size() {
    return jlibapogeeJNI.Uint16Vector_size(swigCPtr, this);
  }

  public long capacity() {
    return jlibapogeeJNI.Uint16Vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    jlibapogeeJNI.Uint16Vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return jlibapogeeJNI.Uint16Vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    jlibapogeeJNI.Uint16Vector_clear(swigCPtr, this);
  }

  public void add(int x) {
    jlibapogeeJNI.Uint16Vector_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return jlibapogeeJNI.Uint16Vector_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    jlibapogeeJNI.Uint16Vector_set(swigCPtr, this, i, val);
  }

}
