# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pylibapogee', [dirname(__file__)])
        except ImportError:
            import _pylibapogee
            return _pylibapogee
        if fp is not None:
            try:
                _mod = imp.load_module('_pylibapogee', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pylibapogee = swig_import_helper()
    del swig_import_helper
else:
    import _pylibapogee
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class ApogeeCam(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ApogeeCam, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ApogeeCam, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pylibapogee.delete_ApogeeCam
    __del__ = lambda self : None;
    def Reset(self): return _pylibapogee.ApogeeCam_Reset(self)
    def ReadReg(self, *args): return _pylibapogee.ApogeeCam_ReadReg(self, *args)
    def WriteReg(self, *args): return _pylibapogee.ApogeeCam_WriteReg(self, *args)
    def SetRoiNumRows(self, *args): return _pylibapogee.ApogeeCam_SetRoiNumRows(self, *args)
    def SetRoiNumCols(self, *args): return _pylibapogee.ApogeeCam_SetRoiNumCols(self, *args)
    def GetRoiNumRows(self): return _pylibapogee.ApogeeCam_GetRoiNumRows(self)
    def GetRoiNumCols(self): return _pylibapogee.ApogeeCam_GetRoiNumCols(self)
    def SetRoiStartRow(self, *args): return _pylibapogee.ApogeeCam_SetRoiStartRow(self, *args)
    def SetRoiStartCol(self, *args): return _pylibapogee.ApogeeCam_SetRoiStartCol(self, *args)
    def GetRoiStartRow(self): return _pylibapogee.ApogeeCam_GetRoiStartRow(self)
    def GetRoiStartCol(self): return _pylibapogee.ApogeeCam_GetRoiStartCol(self)
    def SetRoiBinRow(self, *args): return _pylibapogee.ApogeeCam_SetRoiBinRow(self, *args)
    def GetRoiBinRow(self): return _pylibapogee.ApogeeCam_GetRoiBinRow(self)
    def SetRoiBinCol(self, *args): return _pylibapogee.ApogeeCam_SetRoiBinCol(self, *args)
    def GetRoiBinCol(self): return _pylibapogee.ApogeeCam_GetRoiBinCol(self)
    def GetFirmwareRev(self): return _pylibapogee.ApogeeCam_GetFirmwareRev(self)
    def SetImageCount(self, *args): return _pylibapogee.ApogeeCam_SetImageCount(self, *args)
    def GetImageCount(self): return _pylibapogee.ApogeeCam_GetImageCount(self)
    def GetImgSequenceCount(self): return _pylibapogee.ApogeeCam_GetImgSequenceCount(self)
    def SetSequenceDelay(self, *args): return _pylibapogee.ApogeeCam_SetSequenceDelay(self, *args)
    def GetSequenceDelay(self): return _pylibapogee.ApogeeCam_GetSequenceDelay(self)
    def SetVariableSequenceDelay(self, *args): return _pylibapogee.ApogeeCam_SetVariableSequenceDelay(self, *args)
    def GetVariableSequenceDelay(self): return _pylibapogee.ApogeeCam_GetVariableSequenceDelay(self)
    def SetTdiRate(self, *args): return _pylibapogee.ApogeeCam_SetTdiRate(self, *args)
    def GetTdiRate(self): return _pylibapogee.ApogeeCam_GetTdiRate(self)
    def SetTdiRows(self, *args): return _pylibapogee.ApogeeCam_SetTdiRows(self, *args)
    def GetTdiRows(self): return _pylibapogee.ApogeeCam_GetTdiRows(self)
    def GetTdiCounter(self): return _pylibapogee.ApogeeCam_GetTdiCounter(self)
    def SetTdiBinningRows(self, *args): return _pylibapogee.ApogeeCam_SetTdiBinningRows(self, *args)
    def GetTdiBinningRows(self): return _pylibapogee.ApogeeCam_GetTdiBinningRows(self)
    def SetKineticsSectionHeight(self, *args): return _pylibapogee.ApogeeCam_SetKineticsSectionHeight(self, *args)
    def GetKineticsSectionHeight(self): return _pylibapogee.ApogeeCam_GetKineticsSectionHeight(self)
    def SetKineticsSections(self, *args): return _pylibapogee.ApogeeCam_SetKineticsSections(self, *args)
    def GetKineticsSections(self): return _pylibapogee.ApogeeCam_GetKineticsSections(self)
    def SetKineticsShiftInterval(self, *args): return _pylibapogee.ApogeeCam_SetKineticsShiftInterval(self, *args)
    def GetKineticsShiftInterval(self): return _pylibapogee.ApogeeCam_GetKineticsShiftInterval(self)
    def SetShutterStrobePosition(self, *args): return _pylibapogee.ApogeeCam_SetShutterStrobePosition(self, *args)
    def GetShutterStrobePosition(self): return _pylibapogee.ApogeeCam_GetShutterStrobePosition(self)
    def SetShutterStrobePeriod(self, *args): return _pylibapogee.ApogeeCam_SetShutterStrobePeriod(self, *args)
    def GetShutterStrobePeriod(self): return _pylibapogee.ApogeeCam_GetShutterStrobePeriod(self)
    def SetShutterCloseDelay(self, *args): return _pylibapogee.ApogeeCam_SetShutterCloseDelay(self, *args)
    def GetShutterCloseDelay(self): return _pylibapogee.ApogeeCam_GetShutterCloseDelay(self)
    def SetCoolerBackoffPoint(self, *args): return _pylibapogee.ApogeeCam_SetCoolerBackoffPoint(self, *args)
    def GetCoolerBackoffPoint(self): return _pylibapogee.ApogeeCam_GetCoolerBackoffPoint(self)
    def SetCoolerSetPoint(self, *args): return _pylibapogee.ApogeeCam_SetCoolerSetPoint(self, *args)
    def GetCoolerSetPoint(self): return _pylibapogee.ApogeeCam_GetCoolerSetPoint(self)
    def GetCameraMode(self): return _pylibapogee.ApogeeCam_GetCameraMode(self)
    def SetCameraMode(self, *args): return _pylibapogee.ApogeeCam_SetCameraMode(self, *args)
    def SetFastSequence(self, *args): return _pylibapogee.ApogeeCam_SetFastSequence(self, *args)
    def IsFastSequenceOn(self): return _pylibapogee.ApogeeCam_IsFastSequenceOn(self)
    def SetBulkDownload(self, *args): return _pylibapogee.ApogeeCam_SetBulkDownload(self, *args)
    def IsBulkDownloadOn(self): return _pylibapogee.ApogeeCam_IsBulkDownloadOn(self)
    def SetPipelineDownload(self, *args): return _pylibapogee.ApogeeCam_SetPipelineDownload(self, *args)
    def IsPipelineDownloadOn(self): return _pylibapogee.ApogeeCam_IsPipelineDownloadOn(self)
    def SetIoPortAssignment(self, *args): return _pylibapogee.ApogeeCam_SetIoPortAssignment(self, *args)
    def GetIoPortAssignment(self): return _pylibapogee.ApogeeCam_GetIoPortAssignment(self)
    def SetIoPortBlankingBits(self, *args): return _pylibapogee.ApogeeCam_SetIoPortBlankingBits(self, *args)
    def GetIoPortBlankingBits(self): return _pylibapogee.ApogeeCam_GetIoPortBlankingBits(self)
    def SetIoPortDirection(self, *args): return _pylibapogee.ApogeeCam_SetIoPortDirection(self, *args)
    def GetIoPortDirection(self): return _pylibapogee.ApogeeCam_GetIoPortDirection(self)
    def SetIoPortData(self, *args): return _pylibapogee.ApogeeCam_SetIoPortData(self, *args)
    def GetIoPortData(self): return _pylibapogee.ApogeeCam_GetIoPortData(self)
    def SetPreFlash(self, *args): return _pylibapogee.ApogeeCam_SetPreFlash(self, *args)
    def GetPreFlash(self): return _pylibapogee.ApogeeCam_GetPreFlash(self)
    def SetExternalTrigger(self, *args): return _pylibapogee.ApogeeCam_SetExternalTrigger(self, *args)
    def IsTriggerNormEachOn(self): return _pylibapogee.ApogeeCam_IsTriggerNormEachOn(self)
    def IsTriggerNormGroupOn(self): return _pylibapogee.ApogeeCam_IsTriggerNormGroupOn(self)
    def IsTriggerTdiKinEachOn(self): return _pylibapogee.ApogeeCam_IsTriggerTdiKinEachOn(self)
    def IsTriggerTdiKinGroupOn(self): return _pylibapogee.ApogeeCam_IsTriggerTdiKinGroupOn(self)
    def IsTriggerExternalShutterOn(self): return _pylibapogee.ApogeeCam_IsTriggerExternalShutterOn(self)
    def IsTriggerExternalReadoutOn(self): return _pylibapogee.ApogeeCam_IsTriggerExternalReadoutOn(self)
    def SetShutterState(self, *args): return _pylibapogee.ApogeeCam_SetShutterState(self, *args)
    def GetShutterState(self): return _pylibapogee.ApogeeCam_GetShutterState(self)
    def IsShutterForcedOpen(self): return _pylibapogee.ApogeeCam_IsShutterForcedOpen(self)
    def IsShutterForcedClosed(self): return _pylibapogee.ApogeeCam_IsShutterForcedClosed(self)
    def IsShutterOpen(self): return _pylibapogee.ApogeeCam_IsShutterOpen(self)
    def SetShutterAmpCtrl(self, *args): return _pylibapogee.ApogeeCam_SetShutterAmpCtrl(self, *args)
    def IsShutterAmpCtrlOn(self): return _pylibapogee.ApogeeCam_IsShutterAmpCtrlOn(self)
    def SetCooler(self, *args): return _pylibapogee.ApogeeCam_SetCooler(self, *args)
    def GetCoolerStatus(self): return _pylibapogee.ApogeeCam_GetCoolerStatus(self)
    def IsCoolerOn(self): return _pylibapogee.ApogeeCam_IsCoolerOn(self)
    def GetTempCcd(self): return _pylibapogee.ApogeeCam_GetTempCcd(self)
    def SetCcdAdcResolution(self, *args): return _pylibapogee.ApogeeCam_SetCcdAdcResolution(self, *args)
    def GetCcdAdcResolution(self): return _pylibapogee.ApogeeCam_GetCcdAdcResolution(self)
    def SetCcdAdcSpeed(self, *args): return _pylibapogee.ApogeeCam_SetCcdAdcSpeed(self, *args)
    def GetCcdAdcSpeed(self): return _pylibapogee.ApogeeCam_GetCcdAdcSpeed(self)
    def GetMaxBinCols(self): return _pylibapogee.ApogeeCam_GetMaxBinCols(self)
    def GetMaxBinRows(self): return _pylibapogee.ApogeeCam_GetMaxBinRows(self)
    def GetMaxImgCols(self): return _pylibapogee.ApogeeCam_GetMaxImgCols(self)
    def GetMaxImgRows(self): return _pylibapogee.ApogeeCam_GetMaxImgRows(self)
    def GetTotalRows(self): return _pylibapogee.ApogeeCam_GetTotalRows(self)
    def GetTotalCols(self): return _pylibapogee.ApogeeCam_GetTotalCols(self)
    def GetNumOverscanCols(self): return _pylibapogee.ApogeeCam_GetNumOverscanCols(self)
    def IsInterline(self): return _pylibapogee.ApogeeCam_IsInterline(self)
    def GetPlatformType(self): return _pylibapogee.ApogeeCam_GetPlatformType(self)
    def SetLedAState(self, *args): return _pylibapogee.ApogeeCam_SetLedAState(self, *args)
    def GetLedAState(self): return _pylibapogee.ApogeeCam_GetLedAState(self)
    def SetLedBState(self, *args): return _pylibapogee.ApogeeCam_SetLedBState(self, *args)
    def GetLedBState(self): return _pylibapogee.ApogeeCam_GetLedBState(self)
    def SetLedMode(self, *args): return _pylibapogee.ApogeeCam_SetLedMode(self, *args)
    def GetLedMode(self): return _pylibapogee.ApogeeCam_GetLedMode(self)
    def GetInfo(self): return _pylibapogee.ApogeeCam_GetInfo(self)
    def GetModel(self): return _pylibapogee.ApogeeCam_GetModel(self)
    def GetSensor(self): return _pylibapogee.ApogeeCam_GetSensor(self)
    def SetFlushCommands(self, *args): return _pylibapogee.ApogeeCam_SetFlushCommands(self, *args)
    def AreFlushCmdsDisabled(self): return _pylibapogee.ApogeeCam_AreFlushCmdsDisabled(self)
    def SetPostExposeFlushing(self, *args): return _pylibapogee.ApogeeCam_SetPostExposeFlushing(self, *args)
    def IsPostExposeFlushingDisabled(self): return _pylibapogee.ApogeeCam_IsPostExposeFlushingDisabled(self)
    def GetPixelWidth(self): return _pylibapogee.ApogeeCam_GetPixelWidth(self)
    def GetPixelHeight(self): return _pylibapogee.ApogeeCam_GetPixelHeight(self)
    def GetMinExposureTime(self): return _pylibapogee.ApogeeCam_GetMinExposureTime(self)
    def GetMaxExposureTime(self): return _pylibapogee.ApogeeCam_GetMaxExposureTime(self)
    def IsColor(self): return _pylibapogee.ApogeeCam_IsColor(self)
    def IsCoolingSupported(self): return _pylibapogee.ApogeeCam_IsCoolingSupported(self)
    def IsCoolingRegulated(self): return _pylibapogee.ApogeeCam_IsCoolingRegulated(self)
    def GetInputVoltage(self): return _pylibapogee.ApogeeCam_GetInputVoltage(self)
    def GetInterfaceType(self): return _pylibapogee.ApogeeCam_GetInterfaceType(self)
    def GetUsbVendorInfo(self, *args): return _pylibapogee.ApogeeCam_GetUsbVendorInfo(self, *args)
    def IsCCD(self): return _pylibapogee.ApogeeCam_IsCCD(self)
    def PauseTimer(self, *args): return _pylibapogee.ApogeeCam_PauseTimer(self, *args)
    def IsSerialASupported(self): return _pylibapogee.ApogeeCam_IsSerialASupported(self)
    def IsSerialBSupported(self): return _pylibapogee.ApogeeCam_IsSerialBSupported(self)
    def SetFlushBinningRows(self, *args): return _pylibapogee.ApogeeCam_SetFlushBinningRows(self, *args)
    def GetFlushBinningRows(self): return _pylibapogee.ApogeeCam_GetFlushBinningRows(self)
    def IsOverscanDigitized(self): return _pylibapogee.ApogeeCam_IsOverscanDigitized(self)
    def SetDigitizeOverscan(self, *args): return _pylibapogee.ApogeeCam_SetDigitizeOverscan(self, *args)
    def SetAdcGain(self, *args): return _pylibapogee.ApogeeCam_SetAdcGain(self, *args)
    def GetAdcGain(self, *args): return _pylibapogee.ApogeeCam_GetAdcGain(self, *args)
    def SetAdcOffset(self, *args): return _pylibapogee.ApogeeCam_SetAdcOffset(self, *args)
    def GetAdcOffset(self, *args): return _pylibapogee.ApogeeCam_GetAdcOffset(self, *args)
    def IsInitialized(self): return _pylibapogee.ApogeeCam_IsInitialized(self)
    def IsConnected(self): return _pylibapogee.ApogeeCam_IsConnected(self)
    def SetAdSimMode(self, *args): return _pylibapogee.ApogeeCam_SetAdSimMode(self, *args)
    def IsAdSimModeOn(self): return _pylibapogee.ApogeeCam_IsAdSimModeOn(self)
    def SetLedBrightness(self, *args): return _pylibapogee.ApogeeCam_SetLedBrightness(self, *args)
    def GetLedBrightness(self): return _pylibapogee.ApogeeCam_GetLedBrightness(self)
    def GetDriverVersion(self): return _pylibapogee.ApogeeCam_GetDriverVersion(self)
    def GetUsbFirmwareVersion(self): return _pylibapogee.ApogeeCam_GetUsbFirmwareVersion(self)
    def GetSerialNumber(self): return _pylibapogee.ApogeeCam_GetSerialNumber(self)
    def ReadStrDatabase(self): return _pylibapogee.ApogeeCam_ReadStrDatabase(self)
    def WriteStrDatabase(self, *args): return _pylibapogee.ApogeeCam_WriteStrDatabase(self, *args)
    def OpenConnection(self, *args): return _pylibapogee.ApogeeCam_OpenConnection(self, *args)
    def CloseConnection(self): return _pylibapogee.ApogeeCam_CloseConnection(self)
    def Init(self): return _pylibapogee.ApogeeCam_Init(self)
    def StartExposure(self, *args): return _pylibapogee.ApogeeCam_StartExposure(self, *args)
    def GetStatus(self): return _pylibapogee.ApogeeCam_GetStatus(self)
    def GetImagingStatus(self): return _pylibapogee.ApogeeCam_GetImagingStatus(self)
    def GetImage(self): return _pylibapogee.ApogeeCam_GetImage(self)
    def StopExposure(self, *args): return _pylibapogee.ApogeeCam_StopExposure(self, *args)
    def GetAvailableMemory(self): return _pylibapogee.ApogeeCam_GetAvailableMemory(self)
    def GetNumAds(self): return _pylibapogee.ApogeeCam_GetNumAds(self)
    def GetNumAdChannels(self): return _pylibapogee.ApogeeCam_GetNumAdChannels(self)
    def GetCoolerDrive(self): return _pylibapogee.ApogeeCam_GetCoolerDrive(self)
    def SetFanMode(self, *args): return _pylibapogee.ApogeeCam_SetFanMode(self, *args)
    def GetFanMode(self): return _pylibapogee.ApogeeCam_GetFanMode(self)
    def GetTempHeatsink(self): return _pylibapogee.ApogeeCam_GetTempHeatsink(self)
    def UpdateAlta(self, *args): return _pylibapogee.ApogeeCam_UpdateAlta(self, *args)
    def UpdateAscentOrAltaF(self, *args): return _pylibapogee.ApogeeCam_UpdateAscentOrAltaF(self, *args)
    def UpdateAspen(self, *args): return _pylibapogee.ApogeeCam_UpdateAspen(self, *args)
ApogeeCam_swigregister = _pylibapogee.ApogeeCam_swigregister
ApogeeCam_swigregister(ApogeeCam)

class CamGen2Base(ApogeeCam):
    __swig_setmethods__ = {}
    for _s in [ApogeeCam]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CamGen2Base, name, value)
    __swig_getmethods__ = {}
    for _s in [ApogeeCam]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, CamGen2Base, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pylibapogee.delete_CamGen2Base
    __del__ = lambda self : None;
    def GetStatus(self): return _pylibapogee.CamGen2Base_GetStatus(self)
    def GetImagingStatus(self): return _pylibapogee.CamGen2Base_GetImagingStatus(self)
    def GetImage(self): return _pylibapogee.CamGen2Base_GetImage(self)
    def StopExposure(self, *args): return _pylibapogee.CamGen2Base_StopExposure(self, *args)
    def GetAvailableMemory(self): return _pylibapogee.CamGen2Base_GetAvailableMemory(self)
    def GetNumAds(self): return _pylibapogee.CamGen2Base_GetNumAds(self)
    def GetCoolerDrive(self): return _pylibapogee.CamGen2Base_GetCoolerDrive(self)
    def GetTempHeatsink(self): return _pylibapogee.CamGen2Base_GetTempHeatsink(self)
CamGen2Base_swigregister = _pylibapogee.CamGen2Base_swigregister
CamGen2Base_swigregister(CamGen2Base)

class Alta(ApogeeCam):
    __swig_setmethods__ = {}
    for _s in [ApogeeCam]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Alta, name, value)
    __swig_getmethods__ = {}
    for _s in [ApogeeCam]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Alta, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pylibapogee.new_Alta()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pylibapogee.delete_Alta
    __del__ = lambda self : None;
    def OpenConnection(self, *args): return _pylibapogee.Alta_OpenConnection(self, *args)
    def CloseConnection(self): return _pylibapogee.Alta_CloseConnection(self)
    def Init(self): return _pylibapogee.Alta_Init(self)
    def StartExposure(self, *args): return _pylibapogee.Alta_StartExposure(self, *args)
    def GetStatus(self): return _pylibapogee.Alta_GetStatus(self)
    def GetImagingStatus(self): return _pylibapogee.Alta_GetImagingStatus(self)
    def GetImage(self): return _pylibapogee.Alta_GetImage(self)
    def StopExposure(self, *args): return _pylibapogee.Alta_StopExposure(self, *args)
    def GetAvailableMemory(self): return _pylibapogee.Alta_GetAvailableMemory(self)
    def SetCcdAdc12BitGain(self, *args): return _pylibapogee.Alta_SetCcdAdc12BitGain(self, *args)
    def SetCcdAdc12BitOffset(self, *args): return _pylibapogee.Alta_SetCcdAdc12BitOffset(self, *args)
    def GetCcdAdc12BitGain(self): return _pylibapogee.Alta_GetCcdAdc12BitGain(self)
    def GetCcdAdc12BitOffset(self): return _pylibapogee.Alta_GetCcdAdc12BitOffset(self)
    def GetCcdAdc16BitGain(self): return _pylibapogee.Alta_GetCcdAdc16BitGain(self)
    def GetNumAds(self): return _pylibapogee.Alta_GetNumAds(self)
    def GetNumAdChannels(self): return _pylibapogee.Alta_GetNumAdChannels(self)
    def GetCoolerDrive(self): return _pylibapogee.Alta_GetCoolerDrive(self)
    def SetFanMode(self, *args): return _pylibapogee.Alta_SetFanMode(self, *args)
    def GetFanMode(self): return _pylibapogee.Alta_GetFanMode(self)
    def GetTempHeatsink(self): return _pylibapogee.Alta_GetTempHeatsink(self)
    def GetMacAddress(self): return _pylibapogee.Alta_GetMacAddress(self)
    def OpenSerial(self, *args): return _pylibapogee.Alta_OpenSerial(self, *args)
    def CloseSerial(self, *args): return _pylibapogee.Alta_CloseSerial(self, *args)
    def SetSerialBaudRate(self, *args): return _pylibapogee.Alta_SetSerialBaudRate(self, *args)
    def GetSerialBaudRate(self, *args): return _pylibapogee.Alta_GetSerialBaudRate(self, *args)
    def GetSerialFlowControl(self, *args): return _pylibapogee.Alta_GetSerialFlowControl(self, *args)
    def SetSerialFlowControl(self, *args): return _pylibapogee.Alta_SetSerialFlowControl(self, *args)
    def GetSerialParity(self, *args): return _pylibapogee.Alta_GetSerialParity(self, *args)
    def SetSerialParity(self, *args): return _pylibapogee.Alta_SetSerialParity(self, *args)
    def ReadSerial(self, *args): return _pylibapogee.Alta_ReadSerial(self, *args)
    def WriteSerial(self, *args): return _pylibapogee.Alta_WriteSerial(self, *args)
Alta_swigregister = _pylibapogee.Alta_swigregister
Alta_swigregister(Alta)

class ApogeeFilterWheel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ApogeeFilterWheel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ApogeeFilterWheel, name)
    __repr__ = _swig_repr
    UNKNOWN_TYPE = _pylibapogee.ApogeeFilterWheel_UNKNOWN_TYPE
    FW50_9R = _pylibapogee.ApogeeFilterWheel_FW50_9R
    FW50_7S = _pylibapogee.ApogeeFilterWheel_FW50_7S
    AFW50_10S = _pylibapogee.ApogeeFilterWheel_AFW50_10S
    AFW31_17R = _pylibapogee.ApogeeFilterWheel_AFW31_17R
    UNKNOWN_STATUS = _pylibapogee.ApogeeFilterWheel_UNKNOWN_STATUS
    NOT_CONNECTED = _pylibapogee.ApogeeFilterWheel_NOT_CONNECTED
    READY = _pylibapogee.ApogeeFilterWheel_READY
    ACTIVE = _pylibapogee.ApogeeFilterWheel_ACTIVE
    def __init__(self): 
        this = _pylibapogee.new_ApogeeFilterWheel()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pylibapogee.delete_ApogeeFilterWheel
    __del__ = lambda self : None;
    def Init(self, *args): return _pylibapogee.ApogeeFilterWheel_Init(self, *args)
    def Close(self): return _pylibapogee.ApogeeFilterWheel_Close(self)
    def GetVendorId(self): return _pylibapogee.ApogeeFilterWheel_GetVendorId(self)
    def GetProductId(self): return _pylibapogee.ApogeeFilterWheel_GetProductId(self)
    def GetDeviceId(self): return _pylibapogee.ApogeeFilterWheel_GetDeviceId(self)
    def GetUsbFirmwareRev(self): return _pylibapogee.ApogeeFilterWheel_GetUsbFirmwareRev(self)
    def GetType(self): return _pylibapogee.ApogeeFilterWheel_GetType(self)
    def GetName(self): return _pylibapogee.ApogeeFilterWheel_GetName(self)
    def GetStatus(self): return _pylibapogee.ApogeeFilterWheel_GetStatus(self)
    def GetMaxPositions(self): return _pylibapogee.ApogeeFilterWheel_GetMaxPositions(self)
    def SetPosition(self, *args): return _pylibapogee.ApogeeFilterWheel_SetPosition(self, *args)
    def GetPosition(self): return _pylibapogee.ApogeeFilterWheel_GetPosition(self)
ApogeeFilterWheel_swigregister = _pylibapogee.ApogeeFilterWheel_swigregister
ApogeeFilterWheel_swigregister(ApogeeFilterWheel)

class Ascent(CamGen2Base):
    __swig_setmethods__ = {}
    for _s in [CamGen2Base]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Ascent, name, value)
    __swig_getmethods__ = {}
    for _s in [CamGen2Base]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Ascent, name)
    __repr__ = _swig_repr
    FW_UNKNOWN_TYPE = _pylibapogee.Ascent_FW_UNKNOWN_TYPE
    CFW25_6R = _pylibapogee.Ascent_CFW25_6R
    CFW31_8R = _pylibapogee.Ascent_CFW31_8R
    def __init__(self): 
        this = _pylibapogee.new_Ascent()
        try: self.this.append(this)
        except: self.this = this
    def OpenConnection(self, *args): return _pylibapogee.Ascent_OpenConnection(self, *args)
    def CloseConnection(self): return _pylibapogee.Ascent_CloseConnection(self)
    __swig_destroy__ = _pylibapogee.delete_Ascent
    __del__ = lambda self : None;
    def FilterWheelOpen(self, *args): return _pylibapogee.Ascent_FilterWheelOpen(self, *args)
    def FilterWheelClose(self): return _pylibapogee.Ascent_FilterWheelClose(self)
    def SetFilterWheelPos(self, *args): return _pylibapogee.Ascent_SetFilterWheelPos(self, *args)
    def GetFilterWheelPos(self): return _pylibapogee.Ascent_GetFilterWheelPos(self)
    def GetFilterWheelStatus(self): return _pylibapogee.Ascent_GetFilterWheelStatus(self)
    def GetFilterWheelType(self): return _pylibapogee.Ascent_GetFilterWheelType(self)
    def GetFilterWheelName(self): return _pylibapogee.Ascent_GetFilterWheelName(self)
    def GetFilterWheelMaxPositions(self): return _pylibapogee.Ascent_GetFilterWheelMaxPositions(self)
    def StartExposure(self, *args): return _pylibapogee.Ascent_StartExposure(self, *args)
    def GetNumAdChannels(self): return _pylibapogee.Ascent_GetNumAdChannels(self)
    def Init(self): return _pylibapogee.Ascent_Init(self)
    def IsDualReadoutSupported(self): return _pylibapogee.Ascent_IsDualReadoutSupported(self)
    def SetDualReadout(self, *args): return _pylibapogee.Ascent_SetDualReadout(self, *args)
    def GetDualReadout(self): return _pylibapogee.Ascent_GetDualReadout(self)
    def GetFanMode(self): return _pylibapogee.Ascent_GetFanMode(self)
    def SetFanMode(self, *args): return _pylibapogee.Ascent_SetFanMode(self, *args)
Ascent_swigregister = _pylibapogee.Ascent_swigregister
Ascent_swigregister(Ascent)

class AltaF(CamGen2Base):
    __swig_setmethods__ = {}
    for _s in [CamGen2Base]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AltaF, name, value)
    __swig_getmethods__ = {}
    for _s in [CamGen2Base]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AltaF, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pylibapogee.new_AltaF()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pylibapogee.delete_AltaF
    __del__ = lambda self : None;
    def OpenConnection(self, *args): return _pylibapogee.AltaF_OpenConnection(self, *args)
    def CloseConnection(self): return _pylibapogee.AltaF_CloseConnection(self)
    def StartExposure(self, *args): return _pylibapogee.AltaF_StartExposure(self, *args)
    def GetNumAdChannels(self): return _pylibapogee.AltaF_GetNumAdChannels(self)
    def Init(self): return _pylibapogee.AltaF_Init(self)
    def GetFanMode(self): return _pylibapogee.AltaF_GetFanMode(self)
    def SetFanMode(self, *args): return _pylibapogee.AltaF_SetFanMode(self, *args)
AltaF_swigregister = _pylibapogee.AltaF_swigregister
AltaF_swigregister(AltaF)

class StrDb(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StrDb, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StrDb, name)
    __repr__ = _swig_repr
    __swig_setmethods__["FactorySn"] = _pylibapogee.StrDb_FactorySn_set
    __swig_getmethods__["FactorySn"] = _pylibapogee.StrDb_FactorySn_get
    if _newclass:FactorySn = _swig_property(_pylibapogee.StrDb_FactorySn_get, _pylibapogee.StrDb_FactorySn_set)
    __swig_setmethods__["CustomerSn"] = _pylibapogee.StrDb_CustomerSn_set
    __swig_getmethods__["CustomerSn"] = _pylibapogee.StrDb_CustomerSn_get
    if _newclass:CustomerSn = _swig_property(_pylibapogee.StrDb_CustomerSn_get, _pylibapogee.StrDb_CustomerSn_set)
    __swig_setmethods__["Id"] = _pylibapogee.StrDb_Id_set
    __swig_getmethods__["Id"] = _pylibapogee.StrDb_Id_get
    if _newclass:Id = _swig_property(_pylibapogee.StrDb_Id_get, _pylibapogee.StrDb_Id_set)
    __swig_setmethods__["Platform"] = _pylibapogee.StrDb_Platform_set
    __swig_getmethods__["Platform"] = _pylibapogee.StrDb_Platform_get
    if _newclass:Platform = _swig_property(_pylibapogee.StrDb_Platform_get, _pylibapogee.StrDb_Platform_set)
    __swig_setmethods__["PartNum"] = _pylibapogee.StrDb_PartNum_set
    __swig_getmethods__["PartNum"] = _pylibapogee.StrDb_PartNum_get
    if _newclass:PartNum = _swig_property(_pylibapogee.StrDb_PartNum_get, _pylibapogee.StrDb_PartNum_set)
    __swig_setmethods__["Ccd"] = _pylibapogee.StrDb_Ccd_set
    __swig_getmethods__["Ccd"] = _pylibapogee.StrDb_Ccd_get
    if _newclass:Ccd = _swig_property(_pylibapogee.StrDb_Ccd_get, _pylibapogee.StrDb_Ccd_set)
    __swig_setmethods__["CcdSn"] = _pylibapogee.StrDb_CcdSn_set
    __swig_getmethods__["CcdSn"] = _pylibapogee.StrDb_CcdSn_get
    if _newclass:CcdSn = _swig_property(_pylibapogee.StrDb_CcdSn_get, _pylibapogee.StrDb_CcdSn_set)
    __swig_setmethods__["CcdGrade"] = _pylibapogee.StrDb_CcdGrade_set
    __swig_getmethods__["CcdGrade"] = _pylibapogee.StrDb_CcdGrade_get
    if _newclass:CcdGrade = _swig_property(_pylibapogee.StrDb_CcdGrade_get, _pylibapogee.StrDb_CcdGrade_set)
    __swig_setmethods__["ProcBoardRev"] = _pylibapogee.StrDb_ProcBoardRev_set
    __swig_getmethods__["ProcBoardRev"] = _pylibapogee.StrDb_ProcBoardRev_get
    if _newclass:ProcBoardRev = _swig_property(_pylibapogee.StrDb_ProcBoardRev_get, _pylibapogee.StrDb_ProcBoardRev_set)
    __swig_setmethods__["DriveBoardRev"] = _pylibapogee.StrDb_DriveBoardRev_set
    __swig_getmethods__["DriveBoardRev"] = _pylibapogee.StrDb_DriveBoardRev_get
    if _newclass:DriveBoardRev = _swig_property(_pylibapogee.StrDb_DriveBoardRev_get, _pylibapogee.StrDb_DriveBoardRev_set)
    __swig_setmethods__["Shutter"] = _pylibapogee.StrDb_Shutter_set
    __swig_getmethods__["Shutter"] = _pylibapogee.StrDb_Shutter_get
    if _newclass:Shutter = _swig_property(_pylibapogee.StrDb_Shutter_get, _pylibapogee.StrDb_Shutter_set)
    __swig_setmethods__["WindowType"] = _pylibapogee.StrDb_WindowType_set
    __swig_getmethods__["WindowType"] = _pylibapogee.StrDb_WindowType_get
    if _newclass:WindowType = _swig_property(_pylibapogee.StrDb_WindowType_get, _pylibapogee.StrDb_WindowType_set)
    __swig_setmethods__["MechCfg"] = _pylibapogee.StrDb_MechCfg_set
    __swig_getmethods__["MechCfg"] = _pylibapogee.StrDb_MechCfg_get
    if _newclass:MechCfg = _swig_property(_pylibapogee.StrDb_MechCfg_get, _pylibapogee.StrDb_MechCfg_set)
    __swig_setmethods__["MechRev"] = _pylibapogee.StrDb_MechRev_set
    __swig_getmethods__["MechRev"] = _pylibapogee.StrDb_MechRev_get
    if _newclass:MechRev = _swig_property(_pylibapogee.StrDb_MechRev_get, _pylibapogee.StrDb_MechRev_set)
    __swig_setmethods__["CoolingType"] = _pylibapogee.StrDb_CoolingType_set
    __swig_getmethods__["CoolingType"] = _pylibapogee.StrDb_CoolingType_get
    if _newclass:CoolingType = _swig_property(_pylibapogee.StrDb_CoolingType_get, _pylibapogee.StrDb_CoolingType_set)
    __swig_setmethods__["FinishFront"] = _pylibapogee.StrDb_FinishFront_set
    __swig_getmethods__["FinishFront"] = _pylibapogee.StrDb_FinishFront_get
    if _newclass:FinishFront = _swig_property(_pylibapogee.StrDb_FinishFront_get, _pylibapogee.StrDb_FinishFront_set)
    __swig_setmethods__["FinishBack"] = _pylibapogee.StrDb_FinishBack_set
    __swig_getmethods__["FinishBack"] = _pylibapogee.StrDb_FinishBack_get
    if _newclass:FinishBack = _swig_property(_pylibapogee.StrDb_FinishBack_get, _pylibapogee.StrDb_FinishBack_set)
    __swig_setmethods__["MpiRev"] = _pylibapogee.StrDb_MpiRev_set
    __swig_getmethods__["MpiRev"] = _pylibapogee.StrDb_MpiRev_get
    if _newclass:MpiRev = _swig_property(_pylibapogee.StrDb_MpiRev_get, _pylibapogee.StrDb_MpiRev_set)
    __swig_setmethods__["TestDate"] = _pylibapogee.StrDb_TestDate_set
    __swig_getmethods__["TestDate"] = _pylibapogee.StrDb_TestDate_get
    if _newclass:TestDate = _swig_property(_pylibapogee.StrDb_TestDate_get, _pylibapogee.StrDb_TestDate_set)
    __swig_setmethods__["TestedBy"] = _pylibapogee.StrDb_TestedBy_set
    __swig_getmethods__["TestedBy"] = _pylibapogee.StrDb_TestedBy_get
    if _newclass:TestedBy = _swig_property(_pylibapogee.StrDb_TestedBy_get, _pylibapogee.StrDb_TestedBy_set)
    __swig_setmethods__["TestedDllRev"] = _pylibapogee.StrDb_TestedDllRev_set
    __swig_getmethods__["TestedDllRev"] = _pylibapogee.StrDb_TestedDllRev_get
    if _newclass:TestedDllRev = _swig_property(_pylibapogee.StrDb_TestedDllRev_get, _pylibapogee.StrDb_TestedDllRev_set)
    __swig_setmethods__["TestedFwRev"] = _pylibapogee.StrDb_TestedFwRev_set
    __swig_getmethods__["TestedFwRev"] = _pylibapogee.StrDb_TestedFwRev_get
    if _newclass:TestedFwRev = _swig_property(_pylibapogee.StrDb_TestedFwRev_get, _pylibapogee.StrDb_TestedFwRev_set)
    __swig_setmethods__["Gain"] = _pylibapogee.StrDb_Gain_set
    __swig_getmethods__["Gain"] = _pylibapogee.StrDb_Gain_get
    if _newclass:Gain = _swig_property(_pylibapogee.StrDb_Gain_get, _pylibapogee.StrDb_Gain_set)
    __swig_setmethods__["Noise"] = _pylibapogee.StrDb_Noise_set
    __swig_getmethods__["Noise"] = _pylibapogee.StrDb_Noise_get
    if _newclass:Noise = _swig_property(_pylibapogee.StrDb_Noise_get, _pylibapogee.StrDb_Noise_set)
    __swig_setmethods__["Bias"] = _pylibapogee.StrDb_Bias_set
    __swig_getmethods__["Bias"] = _pylibapogee.StrDb_Bias_get
    if _newclass:Bias = _swig_property(_pylibapogee.StrDb_Bias_get, _pylibapogee.StrDb_Bias_set)
    __swig_setmethods__["TestTemp"] = _pylibapogee.StrDb_TestTemp_set
    __swig_getmethods__["TestTemp"] = _pylibapogee.StrDb_TestTemp_get
    if _newclass:TestTemp = _swig_property(_pylibapogee.StrDb_TestTemp_get, _pylibapogee.StrDb_TestTemp_set)
    __swig_setmethods__["DarkCount"] = _pylibapogee.StrDb_DarkCount_set
    __swig_getmethods__["DarkCount"] = _pylibapogee.StrDb_DarkCount_get
    if _newclass:DarkCount = _swig_property(_pylibapogee.StrDb_DarkCount_get, _pylibapogee.StrDb_DarkCount_set)
    __swig_setmethods__["DarkDuration"] = _pylibapogee.StrDb_DarkDuration_set
    __swig_getmethods__["DarkDuration"] = _pylibapogee.StrDb_DarkDuration_get
    if _newclass:DarkDuration = _swig_property(_pylibapogee.StrDb_DarkDuration_get, _pylibapogee.StrDb_DarkDuration_set)
    __swig_setmethods__["DarkTemp"] = _pylibapogee.StrDb_DarkTemp_set
    __swig_getmethods__["DarkTemp"] = _pylibapogee.StrDb_DarkTemp_get
    if _newclass:DarkTemp = _swig_property(_pylibapogee.StrDb_DarkTemp_get, _pylibapogee.StrDb_DarkTemp_set)
    __swig_setmethods__["CoolingDelta"] = _pylibapogee.StrDb_CoolingDelta_set
    __swig_getmethods__["CoolingDelta"] = _pylibapogee.StrDb_CoolingDelta_get
    if _newclass:CoolingDelta = _swig_property(_pylibapogee.StrDb_CoolingDelta_get, _pylibapogee.StrDb_CoolingDelta_set)
    __swig_setmethods__["Ad1Offset"] = _pylibapogee.StrDb_Ad1Offset_set
    __swig_getmethods__["Ad1Offset"] = _pylibapogee.StrDb_Ad1Offset_get
    if _newclass:Ad1Offset = _swig_property(_pylibapogee.StrDb_Ad1Offset_get, _pylibapogee.StrDb_Ad1Offset_set)
    __swig_setmethods__["Ad1Gain"] = _pylibapogee.StrDb_Ad1Gain_set
    __swig_getmethods__["Ad1Gain"] = _pylibapogee.StrDb_Ad1Gain_get
    if _newclass:Ad1Gain = _swig_property(_pylibapogee.StrDb_Ad1Gain_get, _pylibapogee.StrDb_Ad1Gain_set)
    __swig_setmethods__["Ad2Offset"] = _pylibapogee.StrDb_Ad2Offset_set
    __swig_getmethods__["Ad2Offset"] = _pylibapogee.StrDb_Ad2Offset_get
    if _newclass:Ad2Offset = _swig_property(_pylibapogee.StrDb_Ad2Offset_get, _pylibapogee.StrDb_Ad2Offset_set)
    __swig_setmethods__["Ad2Gain"] = _pylibapogee.StrDb_Ad2Gain_set
    __swig_getmethods__["Ad2Gain"] = _pylibapogee.StrDb_Ad2Gain_get
    if _newclass:Ad2Gain = _swig_property(_pylibapogee.StrDb_Ad2Gain_get, _pylibapogee.StrDb_Ad2Gain_set)
    __swig_setmethods__["Rma1"] = _pylibapogee.StrDb_Rma1_set
    __swig_getmethods__["Rma1"] = _pylibapogee.StrDb_Rma1_get
    if _newclass:Rma1 = _swig_property(_pylibapogee.StrDb_Rma1_get, _pylibapogee.StrDb_Rma1_set)
    __swig_setmethods__["Rma2"] = _pylibapogee.StrDb_Rma2_set
    __swig_getmethods__["Rma2"] = _pylibapogee.StrDb_Rma2_get
    if _newclass:Rma2 = _swig_property(_pylibapogee.StrDb_Rma2_get, _pylibapogee.StrDb_Rma2_set)
    __swig_setmethods__["Comment1"] = _pylibapogee.StrDb_Comment1_set
    __swig_getmethods__["Comment1"] = _pylibapogee.StrDb_Comment1_get
    if _newclass:Comment1 = _swig_property(_pylibapogee.StrDb_Comment1_get, _pylibapogee.StrDb_Comment1_set)
    __swig_setmethods__["Comment2"] = _pylibapogee.StrDb_Comment2_set
    __swig_getmethods__["Comment2"] = _pylibapogee.StrDb_Comment2_get
    if _newclass:Comment2 = _swig_property(_pylibapogee.StrDb_Comment2_get, _pylibapogee.StrDb_Comment2_set)
    __swig_setmethods__["Comment3"] = _pylibapogee.StrDb_Comment3_set
    __swig_getmethods__["Comment3"] = _pylibapogee.StrDb_Comment3_get
    if _newclass:Comment3 = _swig_property(_pylibapogee.StrDb_Comment3_get, _pylibapogee.StrDb_Comment3_set)
    def __init__(self): 
        this = _pylibapogee.new_StrDb()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pylibapogee.delete_StrDb
    __del__ = lambda self : None;
StrDb_swigregister = _pylibapogee.StrDb_swigregister
StrDb_swigregister(StrDb)


def MkStrVectFromStrDb(*args):
  return _pylibapogee.MkStrVectFromStrDb(*args)
MkStrVectFromStrDb = _pylibapogee.MkStrVectFromStrDb

def MkStrDbFromStrVect(*args):
  return _pylibapogee.MkStrDbFromStrVect(*args)
MkStrDbFromStrVect = _pylibapogee.MkStrDbFromStrVect

def GetNoOpDb():
  return _pylibapogee.GetNoOpDb()
GetNoOpDb = _pylibapogee.GetNoOpDb
class NetDb(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, NetDb, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, NetDb, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Magic"] = _pylibapogee.NetDb_Magic_set
    __swig_getmethods__["Magic"] = _pylibapogee.NetDb_Magic_get
    if _newclass:Magic = _swig_property(_pylibapogee.NetDb_Magic_get, _pylibapogee.NetDb_Magic_set)
    __swig_setmethods__["IP"] = _pylibapogee.NetDb_IP_set
    __swig_getmethods__["IP"] = _pylibapogee.NetDb_IP_get
    if _newclass:IP = _swig_property(_pylibapogee.NetDb_IP_get, _pylibapogee.NetDb_IP_set)
    __swig_setmethods__["Gateway"] = _pylibapogee.NetDb_Gateway_set
    __swig_getmethods__["Gateway"] = _pylibapogee.NetDb_Gateway_get
    if _newclass:Gateway = _swig_property(_pylibapogee.NetDb_Gateway_get, _pylibapogee.NetDb_Gateway_set)
    __swig_setmethods__["Netmask"] = _pylibapogee.NetDb_Netmask_set
    __swig_getmethods__["Netmask"] = _pylibapogee.NetDb_Netmask_get
    if _newclass:Netmask = _swig_property(_pylibapogee.NetDb_Netmask_get, _pylibapogee.NetDb_Netmask_set)
    __swig_setmethods__["Port"] = _pylibapogee.NetDb_Port_set
    __swig_getmethods__["Port"] = _pylibapogee.NetDb_Port_get
    if _newclass:Port = _swig_property(_pylibapogee.NetDb_Port_get, _pylibapogee.NetDb_Port_set)
    __swig_setmethods__["Flags"] = _pylibapogee.NetDb_Flags_set
    __swig_getmethods__["Flags"] = _pylibapogee.NetDb_Flags_get
    if _newclass:Flags = _swig_property(_pylibapogee.NetDb_Flags_get, _pylibapogee.NetDb_Flags_set)
    __swig_setmethods__["MAC"] = _pylibapogee.NetDb_MAC_set
    __swig_getmethods__["MAC"] = _pylibapogee.NetDb_MAC_get
    if _newclass:MAC = _swig_property(_pylibapogee.NetDb_MAC_get, _pylibapogee.NetDb_MAC_set)
    __swig_setmethods__["Timeout"] = _pylibapogee.NetDb_Timeout_set
    __swig_getmethods__["Timeout"] = _pylibapogee.NetDb_Timeout_get
    if _newclass:Timeout = _swig_property(_pylibapogee.NetDb_Timeout_get, _pylibapogee.NetDb_Timeout_set)
    def __init__(self): 
        this = _pylibapogee.new_NetDb()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pylibapogee.delete_NetDb
    __del__ = lambda self : None;
NetDb_swigregister = _pylibapogee.NetDb_swigregister
NetDb_swigregister(NetDb)
cvar = _pylibapogee.cvar
NET_MAGIC_VALID = cvar.NET_MAGIC_VALID


def MkU8VectFromNetDb(*args):
  return _pylibapogee.MkU8VectFromNetDb(*args)
MkU8VectFromNetDb = _pylibapogee.MkU8VectFromNetDb

def MkNetDbFromU8Vect(*args):
  return _pylibapogee.MkNetDbFromU8Vect(*args)
MkNetDbFromU8Vect = _pylibapogee.MkNetDbFromU8Vect
UNKNOWN_INTERFACE = _pylibapogee.UNKNOWN_INTERFACE
USB = _pylibapogee.USB
ETHERNET = _pylibapogee.ETHERNET
UNKNOWN_PLATFORM = _pylibapogee.UNKNOWN_PLATFORM
ALTAU = _pylibapogee.ALTAU
ALTAE = _pylibapogee.ALTAE
ASCENT = _pylibapogee.ASCENT
ASPEN = _pylibapogee.ASPEN
HIC = _pylibapogee.HIC
ALTAF = _pylibapogee.ALTAF
QUAD = _pylibapogee.QUAD

def IsAlta(*args):
  return _pylibapogee.IsAlta(*args)
IsAlta = _pylibapogee.IsAlta

def IsGen2Platform(*args):
  return _pylibapogee.IsGen2Platform(*args)
IsGen2Platform = _pylibapogee.IsGen2Platform

def IsFirmwareRevGood(*args):
  return _pylibapogee.IsFirmwareRevGood(*args)
IsFirmwareRevGood = _pylibapogee.IsFirmwareRevGood

def MaskRawId(*args):
  return _pylibapogee.MaskRawId(*args)
MaskRawId = _pylibapogee.MaskRawId

def GetPlatformType(*args):
  return _pylibapogee.GetPlatformType(*args)
GetPlatformType = _pylibapogee.GetPlatformType

def GetPlatformStr(*args):
  return _pylibapogee.GetPlatformStr(*args)
GetPlatformStr = _pylibapogee.GetPlatformStr

def GetModelStr(*args):
  return _pylibapogee.GetModelStr(*args)
GetModelStr = _pylibapogee.GetModelStr

def GetNoOpFirmwareRev():
  return _pylibapogee.GetNoOpFirmwareRev()
GetNoOpFirmwareRev = _pylibapogee.GetNoOpFirmwareRev
Status_ConnectionError = _pylibapogee.Status_ConnectionError
Status_DataError = _pylibapogee.Status_DataError
Status_PatternError = _pylibapogee.Status_PatternError
Status_Idle = _pylibapogee.Status_Idle
Status_Exposing = _pylibapogee.Status_Exposing
Status_ImagingActive = _pylibapogee.Status_ImagingActive
Status_ImageReady = _pylibapogee.Status_ImageReady
Status_Flushing = _pylibapogee.Status_Flushing
Status_WaitingOnTrigger = _pylibapogee.Status_WaitingOnTrigger
CameraMode_Normal = _pylibapogee.CameraMode_Normal
CameraMode_TDI = _pylibapogee.CameraMode_TDI
CameraMode_Test = _pylibapogee.CameraMode_Test
CameraMode_ExternalTrigger = _pylibapogee.CameraMode_ExternalTrigger
CameraMode_ExternalShutter = _pylibapogee.CameraMode_ExternalShutter
CameraMode_Kinetics = _pylibapogee.CameraMode_Kinetics
CameraMode_Unknown = _pylibapogee.CameraMode_Unknown
Resolution_SixteenBit = _pylibapogee.Resolution_SixteenBit
Resolution_TwelveBit = _pylibapogee.Resolution_TwelveBit
AdcSpeed_Unknown = _pylibapogee.AdcSpeed_Unknown
AdcSpeed_Normal = _pylibapogee.AdcSpeed_Normal
AdcSpeed_Fast = _pylibapogee.AdcSpeed_Fast
AdcSpeed_Video = _pylibapogee.AdcSpeed_Video
CoolerStatus_Off = _pylibapogee.CoolerStatus_Off
CoolerStatus_RampingToSetPoint = _pylibapogee.CoolerStatus_RampingToSetPoint
CoolerStatus_AtSetPoint = _pylibapogee.CoolerStatus_AtSetPoint
CoolerStatus_Revision = _pylibapogee.CoolerStatus_Revision
CoolerStatus_Suspended = _pylibapogee.CoolerStatus_Suspended
FanMode_Off = _pylibapogee.FanMode_Off
FanMode_Low = _pylibapogee.FanMode_Low
FanMode_Medium = _pylibapogee.FanMode_Medium
FanMode_High = _pylibapogee.FanMode_High
FanMode_Unknown = _pylibapogee.FanMode_Unknown
LedState_Expose = _pylibapogee.LedState_Expose
LedState_ImageActive = _pylibapogee.LedState_ImageActive
LedState_Flushing = _pylibapogee.LedState_Flushing
LedState_ExtTriggerWaiting = _pylibapogee.LedState_ExtTriggerWaiting
LedState_ExtTriggerReceived = _pylibapogee.LedState_ExtTriggerReceived
LedState_ExtShutterInput = _pylibapogee.LedState_ExtShutterInput
LedState_ExtStartReadout = _pylibapogee.LedState_ExtStartReadout
LedState_AtTemp = _pylibapogee.LedState_AtTemp
LedState_Unknown = _pylibapogee.LedState_Unknown
LedMode_DisableAll = _pylibapogee.LedMode_DisableAll
LedMode_DisableWhileExpose = _pylibapogee.LedMode_DisableWhileExpose
LedMode_EnableAll = _pylibapogee.LedMode_EnableAll
LedMode_Unknown = _pylibapogee.LedMode_Unknown
TriggerMode_Unknown = _pylibapogee.TriggerMode_Unknown
TriggerMode_Normal = _pylibapogee.TriggerMode_Normal
TriggerMode_TdiKinetics = _pylibapogee.TriggerMode_TdiKinetics
TriggerMode_ExternalShutter = _pylibapogee.TriggerMode_ExternalShutter
TriggerMode_ExternalReadoutIo = _pylibapogee.TriggerMode_ExternalReadoutIo
TriggerType_Unkown = _pylibapogee.TriggerType_Unkown
TriggerType_Each = _pylibapogee.TriggerType_Each
TriggerType_Group = _pylibapogee.TriggerType_Group
ShutterState_Unkown = _pylibapogee.ShutterState_Unkown
ShutterState_Normal = _pylibapogee.ShutterState_Normal
ShutterState_ForceOpen = _pylibapogee.ShutterState_ForceOpen
ShutterState_ForceClosed = _pylibapogee.ShutterState_ForceClosed
ErrorType_Connection = _pylibapogee.ErrorType_Connection
ErrorType_Critical = _pylibapogee.ErrorType_Critical
ErrorType_Serious = _pylibapogee.ErrorType_Serious
ErrorType_Configuration = _pylibapogee.ErrorType_Configuration
ErrorType_InvalidMode = _pylibapogee.ErrorType_InvalidMode
ErrorType_InvalidOperation = _pylibapogee.ErrorType_InvalidOperation
ErrorType_InvalidUsage = _pylibapogee.ErrorType_InvalidUsage
SerialParity_Unknown = _pylibapogee.SerialParity_Unknown
SerialParity_None = _pylibapogee.SerialParity_None
SerialParity_Odd = _pylibapogee.SerialParity_Odd
SerialParity_Even = _pylibapogee.SerialParity_Even
SerialFC_Unknown = _pylibapogee.SerialFC_Unknown
SerialFC_Off = _pylibapogee.SerialFC_Off
SerialFC_On = _pylibapogee.SerialFC_On
class CameraStatusRegs(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CameraStatusRegs, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CameraStatusRegs, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _pylibapogee.new_CameraStatusRegs(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pylibapogee.delete_CameraStatusRegs
    __del__ = lambda self : None;
    def GetTempHeatSink(self): return _pylibapogee.CameraStatusRegs_GetTempHeatSink(self)
    def GetTempCcd(self): return _pylibapogee.CameraStatusRegs_GetTempCcd(self)
    def GetCoolerDrive(self): return _pylibapogee.CameraStatusRegs_GetCoolerDrive(self)
    def GetInputVoltage(self): return _pylibapogee.CameraStatusRegs_GetInputVoltage(self)
    def GetTdiCounter(self): return _pylibapogee.CameraStatusRegs_GetTdiCounter(self)
    def GetSequenceCounter(self): return _pylibapogee.CameraStatusRegs_GetSequenceCounter(self)
    def GetStatus(self): return _pylibapogee.CameraStatusRegs_GetStatus(self)
    def GetuFrame(self): return _pylibapogee.CameraStatusRegs_GetuFrame(self)
    def GetMostRecentFrame(self): return _pylibapogee.CameraStatusRegs_GetMostRecentFrame(self)
    def GetReadyFrame(self): return _pylibapogee.CameraStatusRegs_GetReadyFrame(self)
    def GetCurrentFrame(self): return _pylibapogee.CameraStatusRegs_GetCurrentFrame(self)
    def GetFetchCount(self): return _pylibapogee.CameraStatusRegs_GetFetchCount(self)
    def GetDataAvailFlag(self): return _pylibapogee.CameraStatusRegs_GetDataAvailFlag(self)
    def QueryStatusRegs(self, *args): return _pylibapogee.CameraStatusRegs_QueryStatusRegs(self, *args)
    def GetStatusStr(self): return _pylibapogee.CameraStatusRegs_GetStatusStr(self)
    def Update(self, *args): return _pylibapogee.CameraStatusRegs_Update(self, *args)
CameraStatusRegs_swigregister = _pylibapogee.CameraStatusRegs_swigregister
CameraStatusRegs_swigregister(CameraStatusRegs)
FIRMWARE_PLATFORM_MASK = cvar.FIRMWARE_PLATFORM_MASK
MAX_ALTA_FIRMWARE_REV = cvar.MAX_ALTA_FIRMWARE_REV
MIN_GEN2_FIRMWARE = cvar.MIN_GEN2_FIRMWARE
MAX_GEN2_FIRMWARE = cvar.MAX_GEN2_FIRMWARE
ALTA_CAMERA_ID_MASK = cvar.ALTA_CAMERA_ID_MASK
GEN2_CAMERA_ID_MASK = cvar.GEN2_CAMERA_ID_MASK
NO_OP_FRMWR_REV = cvar.NO_OP_FRMWR_REV

class FindDeviceEthernet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FindDeviceEthernet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FindDeviceEthernet, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pylibapogee.new_FindDeviceEthernet()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pylibapogee.delete_FindDeviceEthernet
    __del__ = lambda self : None;
    def Find(self, *args): return _pylibapogee.FindDeviceEthernet_Find(self, *args)
    def GetElapsedSecs(self): return _pylibapogee.FindDeviceEthernet_GetElapsedSecs(self)
    def GetTimeout(self): return _pylibapogee.FindDeviceEthernet_GetTimeout(self)
FindDeviceEthernet_swigregister = _pylibapogee.FindDeviceEthernet_swigregister
FindDeviceEthernet_swigregister(FindDeviceEthernet)

class FindDeviceUsb(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FindDeviceUsb, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FindDeviceUsb, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _pylibapogee.delete_FindDeviceUsb
    __del__ = lambda self : None;
    def Find(self): return _pylibapogee.FindDeviceUsb_Find(self)
    def __init__(self): 
        this = _pylibapogee.new_FindDeviceUsb()
        try: self.this.append(this)
        except: self.this = this
FindDeviceUsb_swigregister = _pylibapogee.FindDeviceUsb_swigregister
FindDeviceUsb_swigregister(FindDeviceUsb)

class Aspen(CamGen2Base):
    __swig_setmethods__ = {}
    for _s in [CamGen2Base]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Aspen, name, value)
    __swig_getmethods__ = {}
    for _s in [CamGen2Base]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Aspen, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pylibapogee.new_Aspen()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pylibapogee.delete_Aspen
    __del__ = lambda self : None;
    def OpenConnection(self, *args): return _pylibapogee.Aspen_OpenConnection(self, *args)
    def CloseConnection(self): return _pylibapogee.Aspen_CloseConnection(self)
    def StartExposure(self, *args): return _pylibapogee.Aspen_StartExposure(self, *args)
    def GetNumAdChannels(self): return _pylibapogee.Aspen_GetNumAdChannels(self)
    def GetMacAddress(self): return _pylibapogee.Aspen_GetMacAddress(self)
    def Init(self): return _pylibapogee.Aspen_Init(self)
    def GetFanMode(self): return _pylibapogee.Aspen_GetFanMode(self)
    def SetFanMode(self, *args): return _pylibapogee.Aspen_SetFanMode(self, *args)
    def IsDualReadoutSupported(self): return _pylibapogee.Aspen_IsDualReadoutSupported(self)
    def SetDualReadout(self, *args): return _pylibapogee.Aspen_SetDualReadout(self, *args)
    def GetDualReadout(self): return _pylibapogee.Aspen_GetDualReadout(self)
Aspen_swigregister = _pylibapogee.Aspen_swigregister
Aspen_swigregister(Aspen)

class Quad(CamGen2Base):
    __swig_setmethods__ = {}
    for _s in [CamGen2Base]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Quad, name, value)
    __swig_getmethods__ = {}
    for _s in [CamGen2Base]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Quad, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pylibapogee.new_Quad()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pylibapogee.delete_Quad
    __del__ = lambda self : None;
    def OpenConnection(self, *args): return _pylibapogee.Quad_OpenConnection(self, *args)
    def CloseConnection(self): return _pylibapogee.Quad_CloseConnection(self)
    def StartExposure(self, *args): return _pylibapogee.Quad_StartExposure(self, *args)
    def IsPixelReorderOn(self): return _pylibapogee.Quad_IsPixelReorderOn(self)
    def SetPixelReorder(self, *args): return _pylibapogee.Quad_SetPixelReorder(self, *args)
    def GetNumAdChannels(self): return _pylibapogee.Quad_GetNumAdChannels(self)
    def SetIsQuadBit(self): return _pylibapogee.Quad_SetIsQuadBit(self)
    def Init(self): return _pylibapogee.Quad_Init(self)
    def GetFanMode(self): return _pylibapogee.Quad_GetFanMode(self)
    def SetFanMode(self, *args): return _pylibapogee.Quad_SetFanMode(self, *args)
Quad_swigregister = _pylibapogee.Quad_swigregister
Quad_swigregister(Quad)

class HiC(Quad):
    __swig_setmethods__ = {}
    for _s in [Quad]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, HiC, name, value)
    __swig_getmethods__ = {}
    for _s in [Quad]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, HiC, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _pylibapogee.new_HiC()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _pylibapogee.delete_HiC
    __del__ = lambda self : None;
    def SetSerialNumber(self, *args): return _pylibapogee.HiC_SetSerialNumber(self, *args)
    def GetCamInfo(self): return _pylibapogee.HiC_GetCamInfo(self)
    def SetCamInfo(self, *args): return _pylibapogee.HiC_SetCamInfo(self, *args)
    def Get4kby4kImage(self): return _pylibapogee.HiC_Get4kby4kImage(self)
HiC_swigregister = _pylibapogee.HiC_swigregister
HiC_swigregister(HiC)

# This file is compatible with both classic and new-style classes.


