#!/bin/sh
export APOGEEPKG = /opt/apogee
cd libapogee
./configure --prefix=/opt/apogee
make install
cd examples
make clean
make
mv BulkSequence BulkTDI ExternalShutter ExternalTrigger FilterWheel Kinetics MultiCamera SimpleExposure StreamingTDI AscentExample $APOGEEPKG/bin/.

cd ../../apps/CPP

g++ -c -g -fPIC -I. -I/opt/apogee/include/libapogee-2.1/apogee -I/opt/apogee/include -I/usr/include/tcl -DLINUX -DAPOGEE_ALTA apgSampleCmn.cpp
g++ -c -g -fPIC -I. -I/opt/apogee/include/libapogee-2.1/apogee -I/opt/apogee/include -I/usr/include/tcl -DLINUX -DAPOGEE_ALTA test_apogee.cpp
g++ -g -o test_alta test_apogee.o apgSampleCmn.o -L/opt/apogee/lib -lccd -lcfitsio -lapogee -lwcs -lusb-1.0 -lcurl -ltcl

g++ -c -g -fPIC -I. -I/opt/apogee/include/libapogee-2.1/apogee -I/opt/apogee/include -I/usr/include/tcl -DLINUX -DAPOGEE_ASCENT test_apogee.cpp
g++ -g -o test_ascent test_apogee.o apgSampleCmn.o -L/opt/apogee/lib -lccd -lcfitsio -lapogee -lwcs -lusb-1.0 -lcurl -ltcl

g++ -c -g -fPIC -I. -I/opt/apogee/include/libapogee-2.1/apogee -I/opt/apogee/include -I/usr/include/tcl -DLINUX findApogee.cpp
g++ -g -o findApogee apgSampleCmn.o findApogee.o -L/opt/apogee/lib -lccd -lcfitsio -lapogee -lwcs -lusb-1.0 -lcurl -ltcl

g++ -c -g -fPIC -I. -I/opt/apogee/include/libapogee-2.1/apogee -I/opt/apogee/include -I/usr/include/tcl -DLINUX -DAPOGEE_ALTA test_filter.cpp
g++ -g -o filter_alta test_filter.o apgSampleCmn.o -L/opt/apogee/lib -lccd -lcfitsio -lapogee -lwcs -lusb-1.0 -lcurl -ltcl

g++ -c -g -fPIC -I. -I/opt/apogee/include/libapogee-2.1/apogee -I/opt/apogee/include -I/usr/include/tcl -DLINUX -DAPOGEE_ASCENT test_filter.cpp
g++ -g -o filter_alta test_filter.o apgSampleCmn.o -L/opt/apogee/lib -lccd -lcfitsio -lapogee -lwcs -lusb-1.0 -lcurl -ltcl

mv filter_alta filter_ascent findApogee test_alta test_ascent $APOGEEPKG/bin/.

cd ../tcl
/usr/bin/swig -c++ -tcl -I/opt/apogee/include/libapogee-2.1/apogee -v -o tcllibapogee_wrap.cpp tcllibapogee.i
g++ -c -fPIC tcllibapogee_wrap.cpp -fpic -DLINUX -DWall -g -I. -I/usr/include/tcl -I/opt/apogee/include/libapogee-2.1/apogee
g++ -shared -o tcllibapogee.so tcllibapogee_wrap.o  -L/usr/local/lib -lapogee -lusb-1.0 -lcurl -ltcl

cd ../java
swig -c++ -java -I/opt/apogee/include/libapogee-2.1/apogee -v -o Javalibapogee_wrap.cpp Javalibapogee.i
g++ -c -fPIC Javalibapogee_wrap.cpp -I. -I/usr/lib/jvm/java-6-openjdk/include -I/opt/apogee/include/libapogee-2.1/apogee 
g++ -shared -o ApogeeCameraJ.so Javalibapogee_wrap.o  -L/usr/local/lib -lapogee -lusb-1.0 -lcurl
javac *.java
jar cvf ApogeeCamera.jar *.class

cd ../python
autoreconf -if
rm -r build
make distclean
mkdir build
cd build
../configure CPPFLAGS=-I/usr/local/include/libapogee-2.1/apogee
make


wish
set TKLIB /opt/apogee/lib
load $TKLIB/libfitstcl.so
load $TKLIB/libccd.so
load ./tcllibapogee.so
set CAMERAS(0) [Alta]
set it $CAMERAS(0)
$it OpenConnection usb 17 22 0
$it Init
$it StartExposure 1.0 1
$it GetImage


