CFLAGS=-c -mh
CPPFLAGS=-c -mh -Ddebug_move_file -Dno_hardware -Dno_network
LFLAGS=-mh
slalib: addet.obj afin.obj airmas.obj altaz.obj amp.obj ampqk.obj aop.obj \
aoppa.obj aoppat.obj aopqk.obj av2m.obj bear.obj caf2r.obj caldj.obj \
calyd.obj cc2s.obj cc62s.obj cd2tf.obj cldj.obj clyd.obj cr2af.obj \
cr2tf.obj cs2c.obj cs2c6.obj ctf2d.obj ctf2r.obj daf2r.obj dafin.obj \
dat.obj dav2m.obj dbear.obj dbjin.obj dc62s.obj dcc2s.obj dcmpf.obj \
dcs2c.obj dd2tf.obj de2h.obj deuler.obj dfltin.obj dh2e.obj dimxv.obj \
djcal.obj djcl.obj dm2av.obj dmat.obj dmoon.obj dmxm.obj dmxv.obj dr2af.obj \
dr2tf.obj drange.obj dranrm.obj ds2c6.obj ds2tp.obj dsep.obj dt.obj \
dtf2d.obj dtf2r.obj dtp2s.obj dtp2v.obj dtprd.obj dtps2c.obj dtpv2c.obj \
dtt.obj dv2tp.obj dvdv.obj dvn.obj dvxv.obj e2h.obj earth.obj ecleq.obj \
ecmat.obj ecor.obj eg50.obj epb.obj epb2d.obj epco.obj epj.obj epj2d.obj \
eqecl.obj eqeqx.obj eqgal.obj etrms.obj euler.obj evp.obj fitxy.obj \
fk425.obj fk45z.obj fk524.obj fk54z.obj flotin.obj galeq.obj galsup.obj \
ge50.obj geoc.obj gmst.obj gmsta.obj gresid.obj h2e.obj imxv.obj \
intin.obj invf.obj kbj.obj m2av.obj map.obj mappa.obj mapqk.obj mapqkz.obj \
moon.obj mxm.obj mxv.obj nut.obj nutc.obj oap.obj oapqk.obj obs.obj \
pa.obj pcd.obj pda2h.obj pdq2h.obj planet.obj pm.obj prebn.obj prec.obj \
preces.obj precl.obj prenut.obj pvobs.obj pxy.obj random.obj range.obj \
ranorm.obj rcc.obj rdplan.obj refco.obj refro.obj refv.obj refz.obj \
rverot.obj rvgalc.obj rvlg.obj rvlsrd.obj rvlsrk.obj s2tp.obj sep.obj \
smat.obj subet.obj supgal.obj svd.obj svdcov.obj svdsol.obj tp2s.obj \
tp2v.obj tprd.obj tps2c.obj tpv2c.obj unpcd.obj v2tp.obj vdv.obj \
vn.obj vxv.obj wait.obj xy2xy.obj zd.obj
	tlib slalib_c @obj.rsp
