/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public final class ErrorType {
  public final static ErrorType ErrorType_Connection = new ErrorType("ErrorType_Connection", jlibapogeeJNI.ErrorType_Connection_get());
  public final static ErrorType ErrorType_Critical = new ErrorType("ErrorType_Critical", jlibapogeeJNI.ErrorType_Critical_get());
  public final static ErrorType ErrorType_Serious = new ErrorType("ErrorType_Serious", jlibapogeeJNI.ErrorType_Serious_get());
  public final static ErrorType ErrorType_Configuration = new ErrorType("ErrorType_Configuration");
  public final static ErrorType ErrorType_InvalidMode = new ErrorType("ErrorType_InvalidMode");
  public final static ErrorType ErrorType_InvalidOperation = new ErrorType("ErrorType_InvalidOperation");
  public final static ErrorType ErrorType_InvalidUsage = new ErrorType("ErrorType_InvalidUsage");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ErrorType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ErrorType.class + " with value " + swigValue);
  }

  private ErrorType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ErrorType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ErrorType(String swigName, ErrorType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ErrorType[] swigValues = { ErrorType_Connection, ErrorType_Critical, ErrorType_Serious, ErrorType_Configuration, ErrorType_InvalidMode, ErrorType_InvalidOperation, ErrorType_InvalidUsage };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

