/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public class FindDeviceUsb {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FindDeviceUsb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FindDeviceUsb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jlibapogeeJNI.delete_FindDeviceUsb(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String Find() {
    return jlibapogeeJNI.FindDeviceUsb_Find(swigCPtr, this);
  }

  public FindDeviceUsb() {
    this(jlibapogeeJNI.new_FindDeviceUsb(), true);
  }

}
