/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public class FindDeviceEthernet {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FindDeviceEthernet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FindDeviceEthernet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jlibapogeeJNI.delete_FindDeviceEthernet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FindDeviceEthernet() {
    this(jlibapogeeJNI.new_FindDeviceEthernet(), true);
  }

  public String Find(String subnet) {
    return jlibapogeeJNI.FindDeviceEthernet_Find(swigCPtr, this, subnet);
  }

  public int GetElapsedSecs() {
    return jlibapogeeJNI.FindDeviceEthernet_GetElapsedSecs(swigCPtr, this);
  }

  public int GetTimeout() {
    return jlibapogeeJNI.FindDeviceEthernet_GetTimeout(swigCPtr, this);
  }

}
