/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public class StrDb {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StrDb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StrDb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jlibapogeeJNI.delete_StrDb(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFactorySn(String value) {
    jlibapogeeJNI.StrDb_FactorySn_set(swigCPtr, this, value);
  }

  public String getFactorySn() {
    return jlibapogeeJNI.StrDb_FactorySn_get(swigCPtr, this);
  }

  public void setCustomerSn(String value) {
    jlibapogeeJNI.StrDb_CustomerSn_set(swigCPtr, this, value);
  }

  public String getCustomerSn() {
    return jlibapogeeJNI.StrDb_CustomerSn_get(swigCPtr, this);
  }

  public void setId(String value) {
    jlibapogeeJNI.StrDb_Id_set(swigCPtr, this, value);
  }

  public String getId() {
    return jlibapogeeJNI.StrDb_Id_get(swigCPtr, this);
  }

  public void setPlatform(String value) {
    jlibapogeeJNI.StrDb_Platform_set(swigCPtr, this, value);
  }

  public String getPlatform() {
    return jlibapogeeJNI.StrDb_Platform_get(swigCPtr, this);
  }

  public void setPartNum(String value) {
    jlibapogeeJNI.StrDb_PartNum_set(swigCPtr, this, value);
  }

  public String getPartNum() {
    return jlibapogeeJNI.StrDb_PartNum_get(swigCPtr, this);
  }

  public void setCcd(String value) {
    jlibapogeeJNI.StrDb_Ccd_set(swigCPtr, this, value);
  }

  public String getCcd() {
    return jlibapogeeJNI.StrDb_Ccd_get(swigCPtr, this);
  }

  public void setCcdSn(String value) {
    jlibapogeeJNI.StrDb_CcdSn_set(swigCPtr, this, value);
  }

  public String getCcdSn() {
    return jlibapogeeJNI.StrDb_CcdSn_get(swigCPtr, this);
  }

  public void setCcdGrade(String value) {
    jlibapogeeJNI.StrDb_CcdGrade_set(swigCPtr, this, value);
  }

  public String getCcdGrade() {
    return jlibapogeeJNI.StrDb_CcdGrade_get(swigCPtr, this);
  }

  public void setProcBoardRev(String value) {
    jlibapogeeJNI.StrDb_ProcBoardRev_set(swigCPtr, this, value);
  }

  public String getProcBoardRev() {
    return jlibapogeeJNI.StrDb_ProcBoardRev_get(swigCPtr, this);
  }

  public void setDriveBoardRev(String value) {
    jlibapogeeJNI.StrDb_DriveBoardRev_set(swigCPtr, this, value);
  }

  public String getDriveBoardRev() {
    return jlibapogeeJNI.StrDb_DriveBoardRev_get(swigCPtr, this);
  }

  public void setShutter(String value) {
    jlibapogeeJNI.StrDb_Shutter_set(swigCPtr, this, value);
  }

  public String getShutter() {
    return jlibapogeeJNI.StrDb_Shutter_get(swigCPtr, this);
  }

  public void setWindowType(String value) {
    jlibapogeeJNI.StrDb_WindowType_set(swigCPtr, this, value);
  }

  public String getWindowType() {
    return jlibapogeeJNI.StrDb_WindowType_get(swigCPtr, this);
  }

  public void setMechCfg(String value) {
    jlibapogeeJNI.StrDb_MechCfg_set(swigCPtr, this, value);
  }

  public String getMechCfg() {
    return jlibapogeeJNI.StrDb_MechCfg_get(swigCPtr, this);
  }

  public void setMechRev(String value) {
    jlibapogeeJNI.StrDb_MechRev_set(swigCPtr, this, value);
  }

  public String getMechRev() {
    return jlibapogeeJNI.StrDb_MechRev_get(swigCPtr, this);
  }

  public void setCoolingType(String value) {
    jlibapogeeJNI.StrDb_CoolingType_set(swigCPtr, this, value);
  }

  public String getCoolingType() {
    return jlibapogeeJNI.StrDb_CoolingType_get(swigCPtr, this);
  }

  public void setFinishFront(String value) {
    jlibapogeeJNI.StrDb_FinishFront_set(swigCPtr, this, value);
  }

  public String getFinishFront() {
    return jlibapogeeJNI.StrDb_FinishFront_get(swigCPtr, this);
  }

  public void setFinishBack(String value) {
    jlibapogeeJNI.StrDb_FinishBack_set(swigCPtr, this, value);
  }

  public String getFinishBack() {
    return jlibapogeeJNI.StrDb_FinishBack_get(swigCPtr, this);
  }

  public void setMpiRev(String value) {
    jlibapogeeJNI.StrDb_MpiRev_set(swigCPtr, this, value);
  }

  public String getMpiRev() {
    return jlibapogeeJNI.StrDb_MpiRev_get(swigCPtr, this);
  }

  public void setTestDate(String value) {
    jlibapogeeJNI.StrDb_TestDate_set(swigCPtr, this, value);
  }

  public String getTestDate() {
    return jlibapogeeJNI.StrDb_TestDate_get(swigCPtr, this);
  }

  public void setTestedBy(String value) {
    jlibapogeeJNI.StrDb_TestedBy_set(swigCPtr, this, value);
  }

  public String getTestedBy() {
    return jlibapogeeJNI.StrDb_TestedBy_get(swigCPtr, this);
  }

  public void setTestedDllRev(String value) {
    jlibapogeeJNI.StrDb_TestedDllRev_set(swigCPtr, this, value);
  }

  public String getTestedDllRev() {
    return jlibapogeeJNI.StrDb_TestedDllRev_get(swigCPtr, this);
  }

  public void setTestedFwRev(String value) {
    jlibapogeeJNI.StrDb_TestedFwRev_set(swigCPtr, this, value);
  }

  public String getTestedFwRev() {
    return jlibapogeeJNI.StrDb_TestedFwRev_get(swigCPtr, this);
  }

  public void setGain(String value) {
    jlibapogeeJNI.StrDb_Gain_set(swigCPtr, this, value);
  }

  public String getGain() {
    return jlibapogeeJNI.StrDb_Gain_get(swigCPtr, this);
  }

  public void setNoise(String value) {
    jlibapogeeJNI.StrDb_Noise_set(swigCPtr, this, value);
  }

  public String getNoise() {
    return jlibapogeeJNI.StrDb_Noise_get(swigCPtr, this);
  }

  public void setBias(String value) {
    jlibapogeeJNI.StrDb_Bias_set(swigCPtr, this, value);
  }

  public String getBias() {
    return jlibapogeeJNI.StrDb_Bias_get(swigCPtr, this);
  }

  public void setTestTemp(String value) {
    jlibapogeeJNI.StrDb_TestTemp_set(swigCPtr, this, value);
  }

  public String getTestTemp() {
    return jlibapogeeJNI.StrDb_TestTemp_get(swigCPtr, this);
  }

  public void setDarkCount(String value) {
    jlibapogeeJNI.StrDb_DarkCount_set(swigCPtr, this, value);
  }

  public String getDarkCount() {
    return jlibapogeeJNI.StrDb_DarkCount_get(swigCPtr, this);
  }

  public void setDarkDuration(String value) {
    jlibapogeeJNI.StrDb_DarkDuration_set(swigCPtr, this, value);
  }

  public String getDarkDuration() {
    return jlibapogeeJNI.StrDb_DarkDuration_get(swigCPtr, this);
  }

  public void setDarkTemp(String value) {
    jlibapogeeJNI.StrDb_DarkTemp_set(swigCPtr, this, value);
  }

  public String getDarkTemp() {
    return jlibapogeeJNI.StrDb_DarkTemp_get(swigCPtr, this);
  }

  public void setCoolingDelta(String value) {
    jlibapogeeJNI.StrDb_CoolingDelta_set(swigCPtr, this, value);
  }

  public String getCoolingDelta() {
    return jlibapogeeJNI.StrDb_CoolingDelta_get(swigCPtr, this);
  }

  public void setAd1Offset(String value) {
    jlibapogeeJNI.StrDb_Ad1Offset_set(swigCPtr, this, value);
  }

  public String getAd1Offset() {
    return jlibapogeeJNI.StrDb_Ad1Offset_get(swigCPtr, this);
  }

  public void setAd1Gain(String value) {
    jlibapogeeJNI.StrDb_Ad1Gain_set(swigCPtr, this, value);
  }

  public String getAd1Gain() {
    return jlibapogeeJNI.StrDb_Ad1Gain_get(swigCPtr, this);
  }

  public void setAd2Offset(String value) {
    jlibapogeeJNI.StrDb_Ad2Offset_set(swigCPtr, this, value);
  }

  public String getAd2Offset() {
    return jlibapogeeJNI.StrDb_Ad2Offset_get(swigCPtr, this);
  }

  public void setAd2Gain(String value) {
    jlibapogeeJNI.StrDb_Ad2Gain_set(swigCPtr, this, value);
  }

  public String getAd2Gain() {
    return jlibapogeeJNI.StrDb_Ad2Gain_get(swigCPtr, this);
  }

  public void setRma1(String value) {
    jlibapogeeJNI.StrDb_Rma1_set(swigCPtr, this, value);
  }

  public String getRma1() {
    return jlibapogeeJNI.StrDb_Rma1_get(swigCPtr, this);
  }

  public void setRma2(String value) {
    jlibapogeeJNI.StrDb_Rma2_set(swigCPtr, this, value);
  }

  public String getRma2() {
    return jlibapogeeJNI.StrDb_Rma2_get(swigCPtr, this);
  }

  public void setComment1(String value) {
    jlibapogeeJNI.StrDb_Comment1_set(swigCPtr, this, value);
  }

  public String getComment1() {
    return jlibapogeeJNI.StrDb_Comment1_get(swigCPtr, this);
  }

  public void setComment2(String value) {
    jlibapogeeJNI.StrDb_Comment2_set(swigCPtr, this, value);
  }

  public String getComment2() {
    return jlibapogeeJNI.StrDb_Comment2_get(swigCPtr, this);
  }

  public void setComment3(String value) {
    jlibapogeeJNI.StrDb_Comment3_set(swigCPtr, this, value);
  }

  public String getComment3() {
    return jlibapogeeJNI.StrDb_Comment3_get(swigCPtr, this);
  }

  public StrDb() {
    this(jlibapogeeJNI.new_StrDb(), true);
  }

}
