/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public final class TriggerMode {
  public final static TriggerMode TriggerMode_Unknown = new TriggerMode("TriggerMode_Unknown");
  public final static TriggerMode TriggerMode_Normal = new TriggerMode("TriggerMode_Normal");
  public final static TriggerMode TriggerMode_TdiKinetics = new TriggerMode("TriggerMode_TdiKinetics");
  public final static TriggerMode TriggerMode_ExternalShutter = new TriggerMode("TriggerMode_ExternalShutter");
  public final static TriggerMode TriggerMode_ExternalReadoutIo = new TriggerMode("TriggerMode_ExternalReadoutIo");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TriggerMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TriggerMode.class + " with value " + swigValue);
  }

  private TriggerMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TriggerMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TriggerMode(String swigName, TriggerMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TriggerMode[] swigValues = { TriggerMode_Unknown, TriggerMode_Normal, TriggerMode_TdiKinetics, TriggerMode_ExternalShutter, TriggerMode_ExternalReadoutIo };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

