/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public final class AdcSpeed {
  public final static AdcSpeed AdcSpeed_Unknown = new AdcSpeed("AdcSpeed_Unknown");
  public final static AdcSpeed AdcSpeed_Normal = new AdcSpeed("AdcSpeed_Normal");
  public final static AdcSpeed AdcSpeed_Fast = new AdcSpeed("AdcSpeed_Fast");
  public final static AdcSpeed AdcSpeed_Video = new AdcSpeed("AdcSpeed_Video");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static AdcSpeed swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + AdcSpeed.class + " with value " + swigValue);
  }

  private AdcSpeed(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private AdcSpeed(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private AdcSpeed(String swigName, AdcSpeed swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static AdcSpeed[] swigValues = { AdcSpeed_Unknown, AdcSpeed_Normal, AdcSpeed_Fast, AdcSpeed_Video };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

