/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public final class CoolerStatus {
  public final static CoolerStatus CoolerStatus_Off = new CoolerStatus("CoolerStatus_Off", jlibapogeeJNI.CoolerStatus_Off_get());
  public final static CoolerStatus CoolerStatus_RampingToSetPoint = new CoolerStatus("CoolerStatus_RampingToSetPoint", jlibapogeeJNI.CoolerStatus_RampingToSetPoint_get());
  public final static CoolerStatus CoolerStatus_AtSetPoint = new CoolerStatus("CoolerStatus_AtSetPoint", jlibapogeeJNI.CoolerStatus_AtSetPoint_get());
  public final static CoolerStatus CoolerStatus_Revision = new CoolerStatus("CoolerStatus_Revision", jlibapogeeJNI.CoolerStatus_Revision_get());
  public final static CoolerStatus CoolerStatus_Suspended = new CoolerStatus("CoolerStatus_Suspended", jlibapogeeJNI.CoolerStatus_Suspended_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CoolerStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CoolerStatus.class + " with value " + swigValue);
  }

  private CoolerStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CoolerStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CoolerStatus(String swigName, CoolerStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CoolerStatus[] swigValues = { CoolerStatus_Off, CoolerStatus_RampingToSetPoint, CoolerStatus_AtSetPoint, CoolerStatus_Revision, CoolerStatus_Suspended };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

