/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public class HiC extends Quad {
  private long swigCPtr;

  protected HiC(long cPtr, boolean cMemoryOwn) {
    super(jlibapogeeJNI.HiC_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HiC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jlibapogeeJNI.delete_HiC(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HiC() {
    this(jlibapogeeJNI.new_HiC(), true);
  }

  public void SetSerialNumber(String num) {
    jlibapogeeJNI.HiC_SetSerialNumber(swigCPtr, this, num);
  }

  public StrDb GetCamInfo() {
    return new StrDb(jlibapogeeJNI.HiC_GetCamInfo(swigCPtr, this), true);
  }

  public void SetCamInfo(StrDb info) {
    jlibapogeeJNI.HiC_SetCamInfo(swigCPtr, this, StrDb.getCPtr(info), info);
  }

  public void Get4kby4kImage(Uint16Vector out) {
    jlibapogeeJNI.HiC_Get4kby4kImage(swigCPtr, this, Uint16Vector.getCPtr(out), out);
  }

}
