/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public final class SerialParity {
  public final static SerialParity SerialParity_Unknown = new SerialParity("SerialParity_Unknown", jlibapogeeJNI.SerialParity_Unknown_get());
  public final static SerialParity SerialParity_None = new SerialParity("SerialParity_None", jlibapogeeJNI.SerialParity_None_get());
  public final static SerialParity SerialParity_Odd = new SerialParity("SerialParity_Odd", jlibapogeeJNI.SerialParity_Odd_get());
  public final static SerialParity SerialParity_Even = new SerialParity("SerialParity_Even", jlibapogeeJNI.SerialParity_Even_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SerialParity swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SerialParity.class + " with value " + swigValue);
  }

  private SerialParity(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SerialParity(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SerialParity(String swigName, SerialParity swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SerialParity[] swigValues = { SerialParity_Unknown, SerialParity_None, SerialParity_Odd, SerialParity_Even };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

