#!/bin/sh
#
# This is a script for generating DSP code from the utilboot.asm and 
#   utilappl.asm files for the utility board
# 

DOWNLOAD=ROM
INTERFACE=PCI

asm56000 -b -lutilboot.ls utilboot.asm
asm56000 -b -lutilappl.ls -d DOWNLOAD $DOWNLOAD -d INTERFACE $INTERFACE utilappl.asm 
dsplnk -butil.cld -v utilboot.cln utilappl.cln
rm util.lod
cldlod util.cld > util.lod
rm utilboot.cln ; rm utilappl.cln ; rm util.cld

srec -mw util.lod

exit 0
