#!/bin/sh
#
	echo ""
	echo "Assembling DSP code for a 2k E2V CCD42-40 CCD"
	echo ""
#
# DOWNLOAD selects application code to be loaded from EEPROM or 
#   downloaded from the host over the fiber optic link
#
# DOWNLOAD = HOST or ROM

DOWNLOAD=HOST
WAVEFORM_FILE=E2V4240_Fast.waveforms
DST_FILE=timFast

asm56300 -b -ltim.ls -d DOWNLOAD $DOWNLOAD -d WAVEFORM_FILE "$WAVEFORM_FILE" tim.asm
dsplnk -btim.cld -v tim.cln 
rm -f "$DST_FILE".lod
cldlod tim.cld > "$DST_FILE".lod
rm tim.cln ; rm tim.cld

	echo ""
	echo "Created file 'tim.lod' for downloading over optical fiber"
	echo ""
