/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public class CamGen2Base extends ApogeeCam {
  private long swigCPtr;

  protected CamGen2Base(long cPtr, boolean cMemoryOwn) {
    super(jlibapogeeJNI.CamGen2Base_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CamGen2Base obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jlibapogeeJNI.delete_CamGen2Base(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CameraStatusRegs GetStatus() {
    return new CameraStatusRegs(jlibapogeeJNI.CamGen2Base_GetStatus(swigCPtr, this), true);
  }

  public Status GetImagingStatus() {
    return Status.swigToEnum(jlibapogeeJNI.CamGen2Base_GetImagingStatus(swigCPtr, this));
  }

  public void GetImage(Uint16Vector out) {
    jlibapogeeJNI.CamGen2Base_GetImage(swigCPtr, this, Uint16Vector.getCPtr(out), out);
  }

  public void StopExposure(boolean Digitize) {
    jlibapogeeJNI.CamGen2Base_StopExposure(swigCPtr, this, Digitize);
  }

  public long GetAvailableMemory() {
    return jlibapogeeJNI.CamGen2Base_GetAvailableMemory(swigCPtr, this);
  }

  public int GetNumAds() {
    return jlibapogeeJNI.CamGen2Base_GetNumAds(swigCPtr, this);
  }

  public double GetCoolerDrive() {
    return jlibapogeeJNI.CamGen2Base_GetCoolerDrive(swigCPtr, this);
  }

  public double GetTempHeatsink() {
    return jlibapogeeJNI.CamGen2Base_GetTempHeatsink(swigCPtr, this);
  }

}
