/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public final class LedState {
  public final static LedState LedState_Expose = new LedState("LedState_Expose", jlibapogeeJNI.LedState_Expose_get());
  public final static LedState LedState_ImageActive = new LedState("LedState_ImageActive", jlibapogeeJNI.LedState_ImageActive_get());
  public final static LedState LedState_Flushing = new LedState("LedState_Flushing", jlibapogeeJNI.LedState_Flushing_get());
  public final static LedState LedState_ExtTriggerWaiting = new LedState("LedState_ExtTriggerWaiting", jlibapogeeJNI.LedState_ExtTriggerWaiting_get());
  public final static LedState LedState_ExtTriggerReceived = new LedState("LedState_ExtTriggerReceived", jlibapogeeJNI.LedState_ExtTriggerReceived_get());
  public final static LedState LedState_ExtShutterInput = new LedState("LedState_ExtShutterInput", jlibapogeeJNI.LedState_ExtShutterInput_get());
  public final static LedState LedState_ExtStartReadout = new LedState("LedState_ExtStartReadout", jlibapogeeJNI.LedState_ExtStartReadout_get());
  public final static LedState LedState_AtTemp = new LedState("LedState_AtTemp", jlibapogeeJNI.LedState_AtTemp_get());
  public final static LedState LedState_Unknown = new LedState("LedState_Unknown", jlibapogeeJNI.LedState_Unknown_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LedState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LedState.class + " with value " + swigValue);
  }

  private LedState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LedState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LedState(String swigName, LedState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LedState[] swigValues = { LedState_Expose, LedState_ImageActive, LedState_Flushing, LedState_ExtTriggerWaiting, LedState_ExtTriggerReceived, LedState_ExtShutterInput, LedState_ExtStartReadout, LedState_AtTemp, LedState_Unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

