/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.apogee.driver;

public class NetDb {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NetDb(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NetDb obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jlibapogeeJNI.delete_NetDb(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMagic(long value) {
    jlibapogeeJNI.NetDb_Magic_set(swigCPtr, this, value);
  }

  public long getMagic() {
    return jlibapogeeJNI.NetDb_Magic_get(swigCPtr, this);
  }

  public void setIP(SWIGTYPE_p_unsigned_char value) {
    jlibapogeeJNI.NetDb_IP_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getIP() {
    long cPtr = jlibapogeeJNI.NetDb_IP_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setGateway(SWIGTYPE_p_unsigned_char value) {
    jlibapogeeJNI.NetDb_Gateway_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getGateway() {
    long cPtr = jlibapogeeJNI.NetDb_Gateway_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setNetmask(SWIGTYPE_p_unsigned_char value) {
    jlibapogeeJNI.NetDb_Netmask_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getNetmask() {
    long cPtr = jlibapogeeJNI.NetDb_Netmask_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setPort(SWIGTYPE_p_unsigned_char value) {
    jlibapogeeJNI.NetDb_Port_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getPort() {
    long cPtr = jlibapogeeJNI.NetDb_Port_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setFlags(SWIGTYPE_p_unsigned_char value) {
    jlibapogeeJNI.NetDb_Flags_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getFlags() {
    long cPtr = jlibapogeeJNI.NetDb_Flags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setMAC(SWIGTYPE_p_unsigned_char value) {
    jlibapogeeJNI.NetDb_MAC_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getMAC() {
    long cPtr = jlibapogeeJNI.NetDb_MAC_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setTimeout(long value) {
    jlibapogeeJNI.NetDb_Timeout_set(swigCPtr, this, value);
  }

  public long getTimeout() {
    return jlibapogeeJNI.NetDb_Timeout_get(swigCPtr, this);
  }

  public NetDb() {
    this(jlibapogeeJNI.new_NetDb(), true);
  }

}
